---
name: Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run ansible-lint
      uses: docker://cytopia/ansible-lint
      with:
        args: .

    - name: Run yamllint
      uses: docker://cytopia/yamllint
      with:
        args: -c /etc/ansible/yamllint.yaml .
